spring:
  main:
    banner_mode: 'OFF'
  profiles:
    active: production
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dcbapp
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
todo-list:
  check-due-date-time: 60000